version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      DB_HOST: postgresdb
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: mydatabase
      DB_PORT: 5432
    ports:
      - "3000:3000"

volumes:
  pgdata:
